### ISSUE TITLE
filtrar o id das pessoas que mandam mensagem para o bot para que só as pessoas do grupo sejam capazes de executar comandos.

### ISSUE THREAD

**Issue by MrTuckie** [pedrovdsc/romervaldo#1]
Para que não vire bagunça e outras pessoas estranhas tenham acesso ao nosso sistema, o bot vai contar com um filtro de ID's para que só certas pessoas tenham acesso a ele.

**Comment by pedrovdsc** [comment]
Tá no repositório errado, irmão.

https://github.com/pedrovdsc/Meu-Quarto
